kind: pipeline
type: docker
name: default
trigger:
  event:
  - push
volumes:
- name: gopath
  temp: {}

clone:
  disable: true

steps:
- name: myclone
  image: docker:git
  ## If you wanted to solve resolving part
  extra_hosts:
    - "localgitea.local: 172.22.0.2"
  commands:
    - wget http://localgitea.local:3001/shiftedmr/drone_test_world

- name: test
  image: golang:1.17
  volumes:
  - name: gopath
    path: /go  
  commands:
  - echo "helloworld"

- name: build
  image: golang:1.17
  volumes:
  - name: gopath
    path: /go
  commands:
  - echo "this is the build step"
  - echo "auto pass"

---
kind: pipeline
type: docker
name: Promotion test

steps:
- name: test
  image: golang:1.17
  commands:
  - echo "Hey <user>, This is a promotion"
  - sleep 10
  - echo "Guess I'm Done."

trigger:
  event:
  - promote
